# Generated by Django 3.0.7 on 2020-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.TextField(),
        ),
    ]
