# Generated by Django 3.0.7 on 2020-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20200714_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.CharField(max_length=200),
        ),
    ]
